//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.DBFirstModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoryType
    {
        public StoryType()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int StoryTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
    }
}
