//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.DBFirstModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoryInformation
    {
        public StoryInformation()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int StoryId { get; set; }
        public int StoryTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Story { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual UserInformation UserInformation { get; set; }
    }
}
