//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.DBFirstModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public Survey()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int SurveyId { get; set; }
        public Nullable<byte> Age { get; set; }
        public string Location { get; set; }
        public string Sex { get; set; }
        public string Story { get; set; }
    
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
