//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.DBFirstModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.TagsTranslateds = new HashSet<TagsTranslated>();
            this.TagTrees = new HashSet<TagTree>();
            this.TagTrees1 = new HashSet<TagTree>();
            this.Surveys = new HashSet<Survey>();
        }
    
        public int TagId { get; set; }
        public byte TagType { get; set; }
        public string EnglishText { get; set; }
    
        public virtual ICollection<TagsTranslated> TagsTranslateds { get; set; }
        public virtual ICollection<TagTree> TagTrees { get; set; }
        public virtual ICollection<TagTree> TagTrees1 { get; set; }
        public virtual ICollection<Survey> Surveys { get; set; }
    }
}
