//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.DBFirstModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagsTranslated
    {
        public int TagId { get; set; }
        public string LanguageCode { get; set; }
        public string Text { get; set; }
    
        public virtual Tag Tag { get; set; }
    }
}
