//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSite.DBFirstModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public UserInformation()
        {
            this.StoryInformations = new HashSet<StoryInformation>();
        }
    
        public int UserId { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual ICollection<StoryInformation> StoryInformations { get; set; }
    }
}
